---
version : '3.9'

services:

  api:
    container_name: api
    build:
      dockerfile: docker/local/Dockerfile
      context: ../../
    env_file:
      - ../../.env
    ports:
      - '8083:8083'
    volumes:
      - ../../:/code
    command: [uvicorn, src.main:app, --host, 0.0.0.0, --port, '8083', --reload]
    networks:
      - converter_network

networks:
  converter_network:
    driver: bridge
