---
version : '3.9'

services:

  api:
#    image: vladimirbodrin/currency_converter:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    image: vladimirbodrin/currency_converter:master-6189353548
    ports:
      - '8086:8086'

