---
version : '3.9'

services:

  api:
    container_name: api
    build:
      dockerfile: docker/deploy/Dockerfile
      context: ../..
    env_file:
      - ../../.env
    ports:
      - '8086:8086'
    command: [uvicorn, src.main:app, --host, 0.0.0.0, --port, '8086', --reload]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

